language: swift
script:
  - xctool -project Kontinuierlich.xcodeproj -scheme Kontinuierlich -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -project Kontinuierlich.xcodeproj -scheme Kontinuierlich -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
